<h2 style='color:blue' align='center'>Implementation of cost functions in python</h2>

In [27]:
import numpy as np

In [28]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

<h3 style='color:blue'>Implement Mean Absolute Error</h3>

In [29]:
def mae(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp - yt)
    print("Total error is:",total_error)
    mae = total_error/len(y_predicted)
    print("Mean absolute error is:",mae)
    return mae

In [30]:
mae(y_predicted, y_true)

Total error is: 2.5
Mean absolute error is: 0.5


0.5

**Implement same thing using numpy in much easier way**

In [31]:
np.abs(y_predicted-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [32]:
np.mean(np.abs(y_predicted-y_true))

0.5

In [33]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true))

In [34]:
mae_np(y_predicted, y_true)

0.5

<h3 style='color:blue'>Implement Log Loss or Binary Cross Entropy</h3>

In [52]:
np.log([0])

<ipython-input-52-f6e7c0610b57>:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [36]:
np.log([0.0000000000001])

array([-29.93360621])

In [37]:
epsilon = 1e-15

In [38]:
np.log([1e-15])

array([-34.53877639])

In [39]:
y_predicted

array([1, 1, 0, 0, 1])

In [40]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [41]:
1-epsilon

0.999999999999999

In [42]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [43]:
y_predicted_new = np.array(y_predicted_new)

In [44]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [45]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

17.2696280766844

In [46]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [47]:
log_loss(y_true, y_predicted)

17.2696280766844

<h3 style='color:blue'>Mean squared error (or MSE) without using numpy</h3>

In [48]:
import numpy as np

y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

In [49]:
def mse(y_true, y_predicted):
    total_error = 0
    for yt, yp in zip(y_true, y_predicted):
        total_error += (yt-yp)**2
    print("Total Squared Error:",total_error)
    mse = total_error/len(y_true)
    print("Mean Squared Error:",mse)
    return mse

In [50]:
mse(y_true, y_predicted)

Total Squared Error: 1.83
Mean Squared Error: 0.366


0.366

<h3 style='color:blue'>Mean squared error (or MSE) using numpy</h3>

In [51]:
np.mean(np.square(y_true-y_predicted))

0.366