In [1]:
import numpy as np

#### Array operations

In [2]:
array1 = np.array([[2,2],[3,3]])
array2 = np.array([[4,4],[5,5]])

In [3]:
array1, array2

(array([[2, 2],
        [3, 3]]),
 array([[4, 4],
        [5, 5]]))

In [4]:
array1 + array2

array([[6, 6],
       [8, 8]])

In [5]:
array1 * array2

array([[ 8,  8],
       [15, 15]])

In [6]:
array1 / array2

array([[0.5, 0.5],
       [0.6, 0.6]])

In [7]:
2*(array1 * array2)

array([[16, 16],
       [30, 30]])

In [8]:
updated = 2*(array1 * array2)/(array1 + array2)
updated

array([[2.66666667, 2.66666667],
       [3.75      , 3.75      ]])

In [9]:
array1 > array2

array([[False, False],
       [False, False]])

#### HM calculation

In [10]:
num1 = 0.08365510
num2 = 0.08365510
2*num1*num2/(num1+num2)

0.0836551

In [11]:
abs(0.08365510 - 0.08365539499895973)

2.949989597322844e-07

In [12]:
0.08365510-2.949989597322844e-07

0.08365480500104026

In [13]:
-4 > -2

False

In [14]:
array1 = np.array([[2,5],[3,3]])
array2 = np.array([[4,4],[5,5]])

In [15]:
hm = 2*(array1 * array2)/(array1 + array2)
hm

array([[2.66666667, 4.44444444],
       [3.75      , 3.75      ]])

In [16]:
array2 > array1

array([[ True, False],
       [ True,  True]])

In [18]:
math.modf(10.5)

(0.5, 10.0)

In [21]:
import math
def apply(num):
    return math.modf(num)[1]
    
temp = np.vectorize(apply)
temp(hm)

array([[2., 4.],
       [3., 3.]])

In [22]:
def apply1(num):
    return math.modf(num)[0]
    
temp = np.vectorize(apply1)
temp(hm)

array([[0.66666667, 0.44444444],
       [0.75      , 0.75      ]])

In [23]:
arr = [[1.75, -0.212]]
temp(arr)

array([[ 0.75 , -0.212]])

In [24]:
arr1 = np.array([[2,1,3],[-4,0,7]])
#arr2 = np.array([[4,3,5],[-2,2,9]])
arr2 = np.array([[0,-0.5,1],[-6,-2,5]])
arr1, arr2

(array([[ 2,  1,  3],
        [-4,  0,  7]]),
 array([[ 0. , -0.5,  1. ],
        [-6. , -2. ,  5. ]]))

In [25]:
hm = 2*arr1*arr2/(arr1+arr2)
hm

array([[ 0.        , -2.        ,  1.5       ],
       [-4.8       ,  0.        ,  5.83333333]])

In [26]:
def apply_gm(v1,v2): 
    
    if v1==0 or v2==0:
        return v2
    
    elif v1>0 and v2>0:
        hm = 2*v1*v2/(v1+v2)
        min1 = min(v1,v2)
        diff = abs(hm-min1)
        if v2 > v1:
            return v2 + diff
        else:
            return v2 - diff
        
    elif v1<0 and v2<0:
        hm = 2*v1*v2/(v1+v2)
        max1 = max(v1,v2)
        diff = abs(hm-max1)
        if v2 > v1:
            return v2 + diff
        else:
            return v2 - diff
    else:
        return v2
 
call = np.vectorize(apply_gm)

In [182]:
call(arr1, arr2)

array([[ 0.        , -0.5       ,  0.5       ],
       [-6.8       , -2.        ,  4.16666667]])

In [156]:
call(0.000000000000001, 0.000000000000000000054)

array(5.83168509e-24)

In [28]:
def meth(num1, num2):
    print("num1: ", num1, "num2: ", num2, "  ",2*num1*num2/(num1+num2))

In [29]:
call(3, 7)
call(7, 3)
meth(-3, -7)
meth(-7, -3)
meth(-3, 7)
meth(7, -3)
meth(3, -7)
meth(-7, 3)
meth(3, 3)
meth(-3,-3)
meth(7, 7)
meth(-7, -7)

num1:  -3 num2:  -7    -4.2
num1:  -7 num2:  -3    -4.2
num1:  -3 num2:  7    -10.5
num1:  7 num2:  -3    -10.5
num1:  3 num2:  -7    10.5
num1:  -7 num2:  3    10.5
num1:  3 num2:  3    3.0
num1:  -3 num2:  -3    -3.0
num1:  7 num2:  7    7.0
num1:  -7 num2:  -7    -7.0


In [30]:
3>=0 and 4 >=0

True

In [32]:
array1, array2

(array([[2, 5],
        [3, 3]]),
 array([[4, 4],
        [5, 5]]))

In [110]:
num1 = np.array([[-2, 1, 1, 2], [-2, 2, -1, -1]], dtype = 'float32')
num2 = np.array([[1, -2, 2, 1], [-1, -1, -2, 2]], dtype = 'float32')

In [111]:
output = num1 < num2
output

array([[ True, False,  True, False],
       [ True, False, False,  True]])

In [112]:
hm = 2*abs(num1)*abs(num2)/(abs(num1)+abs(num2))
hm

array([[1.3333334, 1.3333334, 1.3333334, 1.3333334],
       [1.3333334, 1.3333334, 1.3333334, 1.3333334]], dtype=float32)

In [113]:
np.modf(hm)

(array([[0.33333337, 0.33333337, 0.33333337, 0.33333337],
        [0.33333337, 0.33333337, 0.33333337, 0.33333337]], dtype=float32),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32))

In [114]:
decimal = np.modf(hm)[0]
decimal

array([[0.33333337, 0.33333337, 0.33333337, 0.33333337],
       [0.33333337, 0.33333337, 0.33333337, 0.33333337]], dtype=float32)

In [115]:
num1, num2, output

(array([[-2.,  1.,  1.,  2.],
        [-2.,  2., -1., -1.]], dtype=float32),
 array([[ 1., -2.,  2.,  1.],
        [-1., -1., -2.,  2.]], dtype=float32),
 array([[ True, False,  True, False],
        [ True, False, False,  True]]))

In [116]:
num2[output] 

array([ 1.,  2., -1.,  2.], dtype=float32)

In [117]:
num2[output] = num2[output] + decimal[output]
num2

array([[ 1.3333334, -2.       ,  2.3333335,  1.       ],
       [-0.6666666, -1.       , -2.       ,  2.3333335]], dtype=float32)

In [118]:
num2[~output] = num2[~output] - decimal[~output]
num2 

array([[ 1.3333334, -2.3333335,  2.3333335,  0.6666666],
       [-0.6666666, -1.3333334, -2.3333335,  2.3333335]], dtype=float32)

In [49]:
import tensorflow as tf 
A = tf.convert_to_tensor([[-2, 1, 1, 2], [-2, 2, -1, -1]])
B = tf.convert_to_tensor([[1, -2, 2, 1], [-1, -1, -2, 2]])
tf.add(A, B)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[-1, -1,  3,  3],
       [-3,  1, -3,  1]])>

In [50]:
A, B

(<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
 array([[-2,  1,  1,  2],
        [-2,  2, -1, -1]])>,
 <tf.Tensor: shape=(2, 4), dtype=int32, numpy=
 array([[ 1, -2,  2,  1],
        [-1, -1, -2,  2]])>)

In [69]:
A.numpy()

array([[-2,  1,  1,  2],
       [-2,  2, -1, -1]])

In [72]:
output =  A < B 
output[0][0]

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [59]:
type(A)

tensorflow.python.framework.ops.EagerTensor

In [68]:
A.numpy()

array([[-2,  1,  1,  2],
       [-2,  2, -1, -1]])

In [71]:
tf.where(A<B)

<tf.Tensor: shape=(4, 2), dtype=int64, numpy=
array([[0, 0],
       [0, 2],
       [1, 0],
       [1, 3]], dtype=int64)>

In [43]:
hm = 2*t1*t2/(t1+t2)
hm

array([[1.3333334, 1.3333334, 1.3333334, 1.3333334],
       [1.3333334, 1.3333334, 1.3333334, 1.3333334]], dtype=float32)

In [128]:
v1 = np.array([[-2, 2, 1, 2], [-2, 2, -1, -1]], dtype = 'float32')
v2 = np.array([[1, -2, 2, np.nan], [-1, np.nan, -2, 2]], dtype = 'float32')

In [129]:
v1, v2

(array([[-2.,  2.,  1.,  2.],
        [-2.,  2., -1., -1.]], dtype=float32),
 array([[ 1., -2.,  2., nan],
        [-1., nan, -2.,  2.]], dtype=float32))

In [130]:
nan_flag = np.isnan(v2) 
nan_flag

array([[False, False, False,  True],
       [False,  True, False, False]])

In [132]:
v2[nan_flag] = v1[nan_flag]
v2

array([[ 1., -2.,  2.,  2.],
       [-1.,  2., -2.,  2.]], dtype=float32)

In [134]:
a = b = 'hi'
a, b

('hi', 'hi')

In [153]:
a = np.array([-1, 0, np.nan, 2, 3], dtype=float)
b = np.array([ 0, np.nan, 0, 2, 2], dtype=float)

In [154]:
num = 2*abs(a)*abs(b)
deno = abs(a)+abs(b)
hm = np.where((num==0 or num==np.nan or deno==0 or deno==np.nan), b, num/deno)
hm

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [147]:
c = np.divide(a, b, out=np.zeros_like(a), where=b!=0)
c

array([0. , 0. , 0. , 1. , 1.5])

In [158]:
z1 = np.array([[-2, 1, 1, 2], [-2, 2, -1, -1]], dtype = 'float32')
z2 = np.array([[1, -2, 2, 1], [-1, -1, -2, 2]], dtype = 'float32')
z1, z2

(array([[-2.,  1.,  1.,  2.],
        [-2.,  2., -1., -1.]], dtype=float32),
 array([[ 1., -2.,  2.,  1.],
        [-1., -1., -2.,  2.]], dtype=float32))

In [160]:
flag = z1 < z2
flag

array([[ True, False,  True, False],
       [ True, False, False,  True]])

In [162]:
numerator = 2*abs(z1)*abs(z2)
denominator = abs(z1)+abs(z2)
hm = np.divide(numerator, denominator, where=denominator!=0)
hm

array([[1.3333334, 1.3333334, 1.3333334, 1.3333334],
       [1.3333334, 1.3333334, 1.3333334, 1.3333334]], dtype=float32)

In [163]:
decimal = np.modf(hm)[0]
decimal

array([[0.33333337, 0.33333337, 0.33333337, 0.33333337],
       [0.33333337, 0.33333337, 0.33333337, 0.33333337]], dtype=float32)

In [164]:
z2[flag] = z2[flag] + decimal[flag]
z2[~flag] = z2[~flag] - decimal[~flag]
z2

array([[ 1.3333334, -2.3333335,  2.3333335,  0.6666666],
       [-0.6666666, -1.3333334, -2.3333335,  2.3333335]], dtype=float32)

(array([[-2.,  0.,  1.,  2.],
        [-2.,  2., -1., -1.]], dtype=float32),
 array([[ 1., -2.,  2.,  1.],
        [-1., -1., nan,  2.]], dtype=float32))

In [180]:
flag = z1 < z2
numerator = 2*abs(z1)*abs(z2)
print("numerator :", numerator)
denominator = abs(z1)+abs(z2)
print("denominator :", denominator)
hm = np.divide(numerator, denominator, out=np.zeros_like(z2), where=denominator)!=0)
decimal = np.modf(hm)[0]
z2[flag] = z2[flag] + decimal[flag]
z2[~flag] = z2[~flag] - decimal[~flag]
z2

numerator : [[5.3333335 0.        4.666667  2.6666665]
 [2.6666665 5.3333335       nan 4.666667 ]]
denominator : [[3.3333335 2.        3.3333335 2.6666665]
 [2.6666665 3.3333335       nan 3.3333335]]


array([[ 1.9333334, -2.       ,  2.7333336,  0.6666666],
       [-0.6666666, -1.9333334,        nan,  2.7333336]], dtype=float32)

In [175]:
0/5

0.0

In [193]:
def apply_hm(v1, v2):     
        if v1==0 or v2==0:
            return v2
        elif v1 > v2:
            t1 = abs(v1)
            t2 = abs(v2)
            hm = 2*t1*t2/(t1+t2)
            deci = np.modf(hm)[0] 
            v2 = v2 - deci
            return v2 
        elif v1 < v2:
            t1 = abs(v1)
            t2 = abs(v2)
            hm = 2*t1*t2/(t1+t2)
            deci = np.modf(hm)[0] 
            v2 = v2 + deci
            return v2 
        else:
            return v2   

In [191]:
z1 = np.array([[-2, 1, 1, 2], [-2, 2, -1, -1]])
z2 = np.array([[1, -2, 2, 1], [-1, -1, -2, 2]])
z1, z2

(array([[-2,  1,  1,  2],
        [-2,  2, -1, -1]]),
 array([[ 1, -2,  2,  1],
        [-1, -1, -2,  2]]))

In [194]:
call_hm = np.vectorize(apply_hm)  
call_hm(z1, z2)    

array([[ 1.33333333, -2.33333333,  2.33333333,  0.66666667],
       [-0.66666667, -1.33333333, -2.33333333,  2.33333333]])

#### Removed part

In [ ]:
python_random.seed(7)
np.random.seed(7)
tf.random.set_seed(7)

In [ ]:
# Get the best of base-line model  
generic_training_error = 0
generic_training_loss = 0

class CustomCallbackGeneric(Callback):  
    def on_epoch_end(self, epoch, logs={}): 
        global generic_training_error
        global generic_training_loss 
        
        generic_training_error = round(logs.get('mae'), 4) 
        generic_training_loss = round(logs.get('loss'), 4)  

In [ ]:
  def on_train_end(self, logs=None):
        global hm_training_error
        global hm_training_loss 
        # Metrics
        hm_training_error = round(logs.get('mae'), 4) 
        hm_training_loss = round(logs.get('loss'), 4)  

In [ ]:
hm_training_error = 0
hm_training_loss = 0

In [ ]:
hm_testing_loss = round(hm_testing[0], 4)
hm_testing_accuracy = round(hm_testing[1], 4) 

In [ ]:
# Training time, Training MAE, Training loss
import csv
class CSVWriter():
    filename = None
    fp = None
    writer = None

    def __init__(self, filename):
        self.filename = filename
        self.fp = open(self.filename, 'w', encoding='utf8')
        self.writer = csv.writer(self.fp, quotechar='"', quoting=csv.QUOTE_ALL, lineterminator='\n')

    def close(self):
        self.fp.close()

    def write(self, elems):
        self.writer.writerow(elems)

    def size(self):
        return os.path.getsize(self.filename)

    def fname(self):
        return self.filename 

In [ ]:
mycsv = CSVWriter('2.MNIST_digits_metrics.csv')
mycsv.write(('Parameters', opti_name, 'HM-based ' + opti_name))
mycsv.write(('Training_time', elapsed_training_time_generic, elapsed_training_time_hm))
mycsv.write(('Training_loss', generic_training_loss, hm_training_loss))
mycsv.write(('Training_accuracy', generic_training_accuracy, hm_training_accuracy))
mycsv.write(('Testing_loss', generic_testing_loss, hm_testing_loss))
mycsv.write(('Testing_accuracy', generic_testing_accuracy, hm_testing_accuracy))
mycsv.close() 

In [ ]:
metrics = pd.read_csv('1.Boston_metrics.csv', index_col=0)
metrics

In [ ]:
metrics = pd.read_csv('2.MNIST_digits_metrics.csv', index_col=0)
metrics
optimizers = [opti_name, 'HM-based ' + opti_name]
Training_time_chart = metrics.iloc[0,:].to_list()
Training_loss_chart = metrics.iloc[1,:].to_list()
Training_accuracy_chart = metrics.iloc[2,:].to_list()
Testing_loss_chart = metrics.iloc[3,:].to_list()
Testing_accuracy_chart = metrics.iloc[4,:].to_list()

In [ ]:
fig, a = plt.subplots(2, 2,figsize=(9,9)) 
#fig.suptitle('Loss and accuracy charts')
bar_colors = ['tab:red', 'tab:blue']
a[0][0].bar(optimizers, Training_loss_chart, color=bar_colors)
a[0][0].set_ylabel('Loss (%)')
a[0][0].set_title('Training_loss') 

a[0][1].bar(optimizers, Testing_loss_chart, color=bar_colors)
a[0][1].set_ylabel('Loss (%)')
a[0][1].set_title('Testing_loss') 

a[1][0].bar(optimizers, Training_accuracy_chart, color=bar_colors)
a[1][0].set_ylabel('Accuracy (%)') 
a[1][0].set_title('Training_accuracy') 

a[1][1].bar(optimizers, Testing_accuracy_chart, color=bar_colors)
a[1][1].set_ylabel('Accuracy (%)')
a[1][1].set_title('Testing_accuracy')  
plt.show()

In [ ]:
plt.bar(optimizers, Training_time_chart, color=bar_colors)
plt.ylabel('Time (in seconds)')
plt.xlabel("Optimizers")
plt.title('Training time') 
plt.show()

In [ ]:
generic_testing_loss = round(generic_testing[0], 4)
generic_testing_error = round(generic_testing[1], 4)

In [ ]:
hm_testing_loss = round(hm_testing[0], 4)
hm_testing_error = round(hm_testing[1], 4) 

In [ ]:

        if epoch < 100:
            r = 1
        elif epoch > 100 and epoch < 200:
            r = 0.85
        elif epoch > 200 and epoch < 300:
            r = 0.75
        else e 
            r = 0.65 