In [12]:
import numpy as np

<h3 style='color:blue'>Calculate profit/loss from revenue and expenses</h3>

In [13]:
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [14]:
revenue, expenses

(array([[180, 200, 220],
        [ 24,  36,  40],
        [ 12,  18,  20]]),
 array([[ 80,  90, 100],
        [ 10,  16,  20],
        [  8,  10,  10]]))

In [15]:
profit = revenue - expenses
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

<h3 style='color:blue'>Calculate total sales from units and price per unit using matrix multiplication</h3>

In [16]:
price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [17]:
price_per_unit, units

(array([1000,  400, 1200]),
 array([[30, 40, 50],
        [ 5, 10, 15],
        [ 2,  5,  7]]))

In [18]:
price_per_unit*units

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [19]:
units*price_per_unit

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

In [21]:
price_per_unit1 = np.array([[1000],[400],[1200]])

In above case numpy is using broadcasting so it expands price_per_unit array from 1 row, 3 columns to 3 row and 3 columns. Correct way to do matrix multiplication is to use dot product as shown below

In [22]:
np.dot(price_per_unit,units)

array([34400, 50000, 64400])

In [23]:
np.dot(units,price_per_unit)

array([106000,  27000,  12400])

In [27]:
import tensorflow as tf
A1 = np.array([1,2,3,-1,-2], dtype='float32')
B1 = np.array([-1,0.5,4,2,-3], dtype='float32')
A = tf.convert_to_tensor(A1)
B = tf.convert_to_tensor(B1)
tf.add(A, B)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([ 0. ,  2.5,  7. ,  1. , -5. ], dtype=float32)>

In [28]:
tf.multiply(A1, B1)

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([-1.,  1., 12., -2.,  6.], dtype=float32)>

In [29]:
tf.divide(A1, B1)

<tf.Tensor: shape=(5,), dtype=float32, numpy=
array([-1.       ,  4.       ,  0.75     , -0.5      ,  0.6666667],
      dtype=float32)>

In [30]:
def apply_hm(v1, v2):     
        if v1==0 or v2==0:
            return v2
        elif v1>0 and v2>0:
            hm = 2*v1*v2/(v1+v2)
            min1 = min(v1,v2)
            diff = abs(hm-min1)
            if v2 > v1:
                return v2 + diff
            else:
                return v2 - diff
        elif v1<0 and v2<0:
            hm = 2*v1*v2/(v1+v2)
            max1 = max(v1,v2)
            diff = abs(hm-max1)
            if v2 > v1:
                return v2 + diff
            else:
                return v2 - diff
        else:
            return v2  

In [31]:
call_hm = np.vectorize(apply_hm) 

In [32]:
call_hm(A1, B1)

array([-1.      ,  0.2     ,  4.428571,  2.      , -3.4     ],
      dtype=float32)

In [33]:
li = [[-1,0.5],[4,2,3]]
li

[[-1, 0.5], [4, 2, 3]]

In [34]:
len(li)

2

In [36]:
final = []
for i in range(len(li)):
    output = tf.convert_to_tensor(np.array(li[i])) 
    print("Tensor ", output)
    print(type(output))
    print(type(output.numpy().tolist()))
    print(output.numpy().tolist())
    #final.append(output.numpy().tolist()+2)
    #final[i]=output.numpy().tolist()  
final

Tensor  tf.Tensor([-1.   0.5], shape=(2,), dtype=float64)
<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'list'>
[-1.0, 0.5]
Tensor  tf.Tensor([4 2 3], shape=(3,), dtype=int32)
<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'list'>
[4, 2, 3]


[]

In [37]:
new = []

In [38]:
new.append([4])

In [39]:
new

[[4]]